---
title: "r语言雨课堂ch8-2（1）"
author: "陈建杰（2022190065）"
date: "2024-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 掷3个骰子,点数之和为8的概率是什么?

0.05
0.10
0.15
0.20
```{r}
n=10000
tou = c(1:6)
S1=0
for(i in 1:n){
x1=sample(tou,3,replace = TRUE)
x1_s = sum(x1)
if(x1_s==8)S1=S1+1
}
p1=S1/n
cat("掷3个骰子,点数之和为8的概率是",p1)
```
选"0.10"


# 掷3个骰子,点数之和为8的概率是什么?
0.05
0.10
0.15
0.20

```{r}

```

跟上面的一样，选“0.10”

# 掷硬币100次,连续得到正面或者反面的次数大于等于10次的概率是多少?
可能会用到如下函数rbinom()或者rle()。
0.077
0.079
0.087
0.089
```{r}
n=100000
s2=0
for(i in 1:n){
  x2 = rbinom(100,1,0.5)
  x2_1 = rle(x2)
  if(any(x2_1$lengths >= 10))s2=s2+1
}
p2 = s2/n
p2 = round(p2, digits = 3)
cat("掷硬币100次,连续得到正面或者反面的次数大于等于10次的概率是",p2)

```
选0.087

# 假设有6个孩子,名字分别为A,B,C,D,E,F,6个孩子随机地排成一排,6个孩子按照字母顺序排列的概率是多少?
0.14
0.014
0.0014
0.00014

```{r}
# 设置模拟次数
n <- 10000

# 用于统计满足条件（按字母顺序排列）的次数
count <- 0

for (i in 1:n) {
    # 生成6个孩子名字的随机排列
    random_permutation <- sample(c("A", "B", "C", "D", "E", "F"), 6, replace = FALSE)

    # 检查是否为按照字母顺序排列（A、B、C、D、E、F）
    if (identical(random_permutation, c("A", "B", "C", "D", "E", "F"))) {
        count <- count + 1
    }
}

# 计算概率
probability <- count / n

probability
```
选"0.0014"

# 假设有6个孩子,其中3个女孩,3个男孩,6个孩子随机地排成一排,3个女孩都排在前面3个位置的概率是多少?
0.05
0.06
0.07
0.08

```{r}
n=10000
s6=0
#1 girl 2 boy
c6 = c(1,1,1,2,2,2)
for(i in 1:n)
{
  x6 = sample(c6,6,replace = FALSE)
  if (identical(x6,c6)==TRUE)s6=s6+1
  
}
s6
p6=s6/n
p6= round(p6,digits =2)
p6
cat("3个女孩都排在前面3个位置的概率是",p6)
```
选“0.05”


# 掷硬币6次,没有两个正面或两个反面在一起的概率是多少?例如,HTHTHT。
0.02
0.03
0.04
0.05

```{r}
n=10000
s7=0
for(i in 1:n){
  x7 = rbinom(6,1,0.5)
  x7_1 = rle(x7)
  if(length(x7_1$values) == 6)s7=s7+1
}
p7 = s7/n
p7 = round(p7, digits = 2)
cat("掷硬币6次,没有两个正面或两个反面在一起的概率是",p7)
```
选“0.03”

# 一幅52张的扑克牌,从中随机抽取5张,5张都是同一花色的概率是多少?
0.001
0.002
0.003
0.004

```{r}
n=1000000
s8=0
c8=c(1:52)
for(i in 1:n){
x8=sample(c8,5,replace = FALSE)
x81=sum(x8 %in% 1:13)
x82=sum(x8 %in% 14:26)
x83=sum(x8 %in% 27:39)
x84=sum(x8 %in% 40:52)
if(x81==5|x82==5|x83==5|x84==5){s8=s8+1}
}
s8
p8 = s8/n
p8 = round(p8, digits = 4)
cat("一幅52张的扑克牌,从中随机抽取5张,5张都是同一花色的概率是",p8)

```
选“0.002”


# 一幅52张的扑克牌,从中随机抽取13张,13张牌中没有Ace,也没有红桃的概率是多少?
0.0016
0.0026
0.0036
0.0046

```{r}
n=1000000
s9=0
c9=c(1:52)
for(i in 1:n){
x9=sample(c9,13,replace = FALSE)
x91 = sum(x9 %in% 1:36)
if(x91==13){s9=s9+1}
}
s9
p9 = s9/n
p9 = round(p9, digits = 4)
cat("一幅52张的扑克牌,从中随机抽取13张,13张牌中没有Ace,也没有红桃的概率是",p9)
```

选"0.0036"